name: Build and Push Docker Image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          echo "=== Building Docker Image ==="
           docker build -t registry.africastalking.dev/136ulk/tailwind-project:latest .
          echo "=== Pushing Docker Image ==="
          docker push registry.africastalking.dev/136ulk/tailwind-project:latest