name: Build and Push Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      - name: Build and Push
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/tailwind-project:latest .
          docker push ${{ secrets.REGISTRY_URL }}/tailwind-project:latest